### ISSUE TITLE
Add serde_json_path

### ISSUE THREAD

**Issue by glyn** [cburgmer/json-path-comparison#141]
This would be particularly useful because it implements RFC 9535.

https://github.com/hiltontj/serde_json_path

https://github.com/KittyMac/Sextant/issues/10#issuecomment-1961207958

**Comment by cburgmer** [comment]
Here are the "bugs" judging by the consensus (not the RFC): https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/Rust_serde_json_path.md
