### ISSUE TITLE
Bump JsonPath.Net to v1.0.0

### ISSUE THREAD

**Issue by glyn** [cburgmer/json-path-comparison#143]
v1.0.0 implements RFC 9535. 

https://github.com/KittyMac/Sextant/issues/10#issuecomment-1961225471

/cc @gregsdennis

**Comment by cburgmer** [comment]
Closed via PR. Thx for raising!

**Comment by gregsdennis** [comment]
@cburgmer the target framework needs to be updated to `net6.0`.  `netcoreapp3.1` is out of support now.  Not sure why you didn't just merge the PR, which included this change.

**Comment by cburgmer** [comment]
Commit 3a122339e232549f91d788adca0f8395d19b322d is there.

I don't use the UI most of the time to rebase + merge commits, as I need to run them locally, first to see if the commit works, second to check-in the artifacts.
