### ISSUE TITLE
Clarify "Array index dot notation on object"

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/json-path-comparison#16]
Currently our own naming somewhat conflates the different notations, especially *Array index dot notation on object* (https://cburgmer.github.io/json-path-comparison/results/array_index_dot_notation_on_object.html) seems incorrect, as this is indeed the dot notation for a path on an object. Calling a query *Array index dot notation* (https://cburgmer.github.io/json-path-comparison/results/array_index_dot_notation.html) also somewhat suggests such a thing is mandated by Goessner's articles.

Let's clarify this.

**Comment by remorhaz** [comment]
In fact, it's not an "array index", it's "numeric property".

**Comment by cburgmer** [comment]
Braindump:

array index slice => array slice

array index union => union

array index => bracket notation

key bracket notation union => union

key bracket notation => bracket notation

key dot notation => dot notation

key dot bracket notation => dot bracket notation

recursive ... => recursive descent and ...

recursive on nested object => dot notation and recursive descent and dot notation

**Comment by cburgmer** [comment]
Key bracket notation union with key ... => union after dot notation

Wildcard bracket notation with key ... => dot notation after wildcard bracket notation

**Comment by cburgmer** [comment]
Not saying some queries couldn't be further clarified, but I believe we now have a robust system for more clarity.
