### ISSUE TITLE
Where is the expected result?

### ISSUE THREAD

**Issue by gregsdennis** [cburgmer/json-path-comparison#25]
First, great page & study.

I'd like to implement this suite in my library to address some of the issues that the suite found with my implementation.  However, I can't find where you store the expected result from your queries.

For example, in https://github.com/cburgmer/json-path-comparison/tree/master/queries/array_index_last you have

- *document.json* that contains the JSON data
- *selector* that contains the JSON Path
- *SCALAR_RESULT* that is an empty file (this doesn't download in a `git clone` operation either)

If I want to run this test in my suite, I need an expected result to compare against.  Where can I find this value?

**Comment by cburgmer** [comment]
Are you looking for https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml? This has every consensus both for list based and scalar based responses.

**Comment by gregsdennis** [comment]
Right, but that's a generated file (by https://github.com/cburgmer/json-path-comparison/blob/master/src/compile_regression_suite.sh).  Where do the consensus values come from?

**Comment by cburgmer** [comment]
Ah, ok. I'm trying to call it out at the bottom of the table. Let me know if this answers the question. Maybe this needs to be put more prominently?

> We execute all available implementations against the same queries. Outcomes are compared across implementations, and judged based on a simple consensus: a majority of half of all implementations (rounded up) plus one is required (guarantees difference of 2 votes even in critical cases). This table makes no statement on the correctness of any of the implementations.

**Comment by gregsdennis** [comment]
Hm... not what I was expecting.  Interesting approach, though.  I suppose I'll have to work out another method to getting the expected result from that regression file you linked.

What is the *SCALAR_RESULT* file?  It's empty and doesn't download with `git clone`.

**Comment by cburgmer** [comment]
Yes, it is just used as a flag. The SCALAR_RESULT is to mark that this kind of query is expected to find only one result at most. This is predefined and not part of the consensus (hoping that authors do at least agree on that).

I'm not sure I understand fully what you need, I'd like to though!

My assumption is that most library authors would want a test suite to check their implementation against. The YAML file is my best guess for that so far.

**Comment by cburgmer** [comment]
As for the consensus bit: My understanding is that a big group of people independently going for the same solution increases the likelihood of that solution to be correct (at least for such a simple thing as an algorithm to look up values). Also, in absence of a standard, this is the best approach to facilitate one.

**Comment by gregsdennis** [comment]
This: https://github.com/gregsdennis/Manatee.Json/blob/path-test-suite/Manatee.Json.Tests/Path/CburgmerFeatureValidationTests.cs

The goal is to get all of these passing (or inconclusive for the non-consensused ones).

**Comment by gregsdennis** [comment]
Honest question:  Would it make sense that Goessner's implementation be the standard?  I mean he created it.  For instance, does his implementation really support things like `$['one','three'].key`?

**Comment by cburgmer** [comment]
Shouldn't Goessner's implementation be standard? Yes absolutely, given your example though his implementation does cover the case: 
https://cburgmer.github.io/json-path-comparison/#key_bracket_notation_union_with_key_on_nested_objects (see JS and PHP for Goessner's take). 

I see it like that:
- The consensus probably follows Goessner's implementation in most cases.
- Goessner's JS and PHP implementations aren't always consistent, see the table.
- If the consensus moves away in some cases, it might be for a good reason, the consensus gives us flexibility to do that, by moving along the majority. 
- If implementations split over the interpretation, there's nothing holding us back from separating factions in the consensus itself.

**Comment by cburgmer** [comment]
To answer your `$['single'quote']` example, not everything that is added is meant ultimately to be supported. I also wanted to capture edge cases and show alternative interpretations currently found in the wild.

**Comment by gregsdennis** [comment]
Okay. Thanks.  I'll continue working on this. I'll have to figure out a way to make some of these as optional (not supported) so they don't kill my build.  Hopefully I can change a few of those `e`s to checks...

**Comment by cburgmer** [comment]
You can use the build report YAML generated for each library to fix current responses, have a look at https://github.com/cburgmer/json-path-comparison#regression-test-suite.

**Comment by cburgmer** [comment]
I took this as a motivation to write down of the questions and answers: https://github.com/cburgmer/json-path-comparison/blob/master/FAQ.md

**Comment by gregsdennis** [comment]
Very nice. :+1:
