### ISSUE TITLE
test case filter_regular_expression also depends on single-equals support

### ISSUE THREAD

**Issue by gregsdennis** [cburgmer/json-path-comparison#26]
The test case `filter_regular_expression` uses `$[?(@.name=~/hello.*/)]` as the query string.  I noticed that there is a separate test for single-equals-for-comparison usage, something I don't plan on supporting.

This test should be updated to use the double-equal operator (`$[?(@.name==~/hello.*/)]`), so that the only the thing being tested is regex support.

**Comment by cburgmer** [comment]
I'm not sure I understand. I ran

`cat queries/filter_regular_expression/document.json | ./src/one_off.sh '$[?(@.name==~/hello.*/)]'`

and this does not seem to be supported by any implementation.

**Comment by gregsdennis** [comment]
Then I guess I don't understand the syntax.  Is `=~` the operator?

**Comment by cburgmer** [comment]
AFAIK `=~` is found in e.g. Bash and Perl. I couldn't find any mention in Goessner's posts.

**Comment by remorhaz** [comment]
At least [bash](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Conditional-Constructs) uses `=~` as operator for regexp matching. Well-known Java implementation [does the same](https://github.com/json-path/JsonPath) (and I used same syntax in my PHP implementation).

**Comment by gregsdennis** [comment]
Cool.  Given the apparently limited use, I'm going to explicitly exclude this case until it gains more traction.  Thanks.
