### ISSUE TITLE
Permission to steal and re-use

### ISSUE THREAD

**Issue by gregsdennis** [cburgmer/json-path-comparison#27]
So, I shared this with the folks over at [JSON Schema](https://github.com/json-schema-org/JSON-Schema-Test-Suite) (of which I'm a part), and they really liked it.  I was wondering if either:

1. If you'd want to join us and build/manage a similar site for JSON Schema, or
2. Mind if we stole and repurposed this ourselves.

Your thoughts?

**Comment by cburgmer** [comment]
Thanks for asking, but in the spirit of Open Source/Free Software: Please re-use, the license is there. Let me know if the license is a problem.

I will continue putting my energy here for now :)

**Comment by gregsdennis** [comment]
No worries.  We'll continue.  I'll let you know how it goes if you like.
