### ISSUE TITLE
Preserve duplicates after filtering in Proposal A

### ISSUE THREAD

**Issue by glyn** [cburgmer/json-path-comparison#47]
It's not clear why Proposal A removes duplicates after filtering. See the following examples:
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_greater_than.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_greater_than_or_equal.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_less_than.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_less_than_or_equal.html
* (counter example?) https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_negation_and_equals.html

I think filtering of an array should preserve ordering and therefore preserve duplicates too.

**Comment by cburgmer** [comment]
I don't think I understand what you mean by duplicates. From the linked examples I can see different response behaviour on numbers `42` vs. strings `"42"`.

So you might be referring to Proposal A not matching strings for numbers and vice versa. Goessner's solution seems to have inherited JavaScript's type conversion logic (by offloading everything to eval or JavaScripts operators directly).

JavaScript's type conversion is highly problematic, so I wanted to step away from this as a default answer, and rather start fresh. Currently being conservative and respecting JSON types and not introducing some definition of equality across types was the simplest way forward.

I'll document the above sentiment (although I'm happy to discuss it!), let me know if I misunderstood.

**Comment by glyn** [comment]
No, it was quote blindness on my part. Thanks!
