### ISSUE TITLE
check and X interpretation is misleading on first glance

### ISSUE THREAD

**Issue by codeniko** [cburgmer/json-path-comparison#5]
Let's face it, you'll look at the chart first before reading the text at the top or the legend at the bottom. I did and I thought checkmark represented "correctness", X represented "incorrectness" result, and `e` represented exceptional errors/crashes. Can these be changed to something clearer? I don't have alternatives at the top of my head but this is something that can be brainstormed for better UX.

It may also be useful to split the `e` with another symbol to track differences between paths that had exceptions (crashes) and those intentionally thrown during path compiling when invalid/unsupported tokens are input (or similar).

**Comment by cburgmer** [comment]
Thanks for your feedback! Happy to talk about the representation.

I agree that the checkmark and X suggest we are talking about correctness, while the explanation of that comparison tries to keep out of that difficult topic by relying on consensus.

To be clear, the current goal of this comparison is just to create visibility and help implementors find issues by sharing test cases, and give guidance on interpretation of the initial post by Goessner. The motivation of the consensus is to drive the discussion towards a shared understanding of the JSONPath specs. 

So, I'd still like to make clear that a substantial majority decided independently to root for a certain understanding. Maybe we find a good pair of symbols to both express that, but also not take an authoritative position.

On the case of errors, I read your point as trying to tell actual errors from _not supported_: Happy to probe into an effective way, but I'm unsure whether this can be easily done independently for all of the tools. Goessner's own implementation for example will return `false` independently of whether a query couldn't be understood or no match was found.

**Comment by cburgmer** [comment]
I've tried to rewrite this more clearly here: https://github.com/cburgmer/json-path-comparison/blob/master/FAQ.md

If we want to make it clearer to where the "correctness" is coming from, all for it, no idea for now though.

As for the 'e' scenario I would refer to #1 .

Closing this for now, please reopen if necessary.
