### ISSUE TITLE
Negative array slice steps in Proposal A

### ISSUE THREAD

**Issue by glyn** [cburgmer/json-path-comparison#55]
Proposal A has the following TODO item:

> `$[::-2]`
>
>No consensus, but if we support `$[::2]` we should probably support this too. The current default values (start `0` and end `len(array)`) do not work for negative steps as the start and end need to be switched.

## Basics

Let's start by agreeing some basic behaviour of the array slice`[start;end;step]` for non-negative `start`, `end`, and `step`:
* `start` is the inclusive starting point of the slice (with `0` meaning the first element of the array)
* `end` is the exclusive end point, or "fence post" (see below), of the slice
* `step` is the value we should add on each iteration, and must be non-zero to avoid an infinite loop (unless `start >= end`)

So, when `step` is positive, the indices of the slice are the same as the values of `i` iterated over by this `for` loop in C:
```
for (i = start; i < end; i = i + step) {
  ...
}
```

Notice that if `start >= end`, the slice is empty. Also, indices which are greater than or equal to the length of the array are discarded.

Some examples are in order:
* `[0:2:1]` applied to `[0,1,2]` produces `[0,1]`
* `[1:1:1]` applied to `[0,1,2]` produces `[]`
* `[2:9:1]` applied to `[0,1,2]` produces `[2]`

## Default values

Any of the three values may be omitted:
* `start` defaults to `0`, so for example `[:2:1]` covers the first two elements of the array 
* `end` defaults to the length of the array, so for example `[1::1]` covers all except the first element of the array
* `step` defaults to `1`, so for example `[1:3:]` covers the second and third elements of the array

These defaults allow contractions such as `[1:]` and even `[:]` and `[::]`.

## Negative values

Now let's see how the notation can be extended to include negative values.

If `start` or `end` are negative, this is simply a shorthand way of indexing from the end of the array. If `start` is negative, the starting index is `len+start` where `len` is the length of the array being sliced. Similarly for `end`. This came from [Göessner](https://goessner.net/articles/JsonPath/) who defines `$..book[-1:]` to be the last book in the array. (Since `0` indexes the first element of an array, it might be tempting to make `-0` index the last element of the array, were it not for the fact that `-0` and `0` are equal, at least when treated as integers.)

But what does a negative `step` mean?

There seem to be three possible interpretations. The first two iterate in the direction `start` to `end`, so I've called them "forwards" interpretations. The third iterates in the direction `end` to `start`, so I've called it the "backwards" interpretation.

### 1. Forwards A

"forwards A" corresponds to the `for` loop:
```
for (i = start; i > end; i = i + step) {
  ...
}
```
The assumptions here are that `start` is still the inclusive starting point, `end` is still the exclusive end point, and to have any hope of a non-empty slice `start > end`.

So, for example, `[2:0:-1]` applied to `[0,1,2]` produces `[2,1]`. ~One problem with this interpretation is that there is no way to include the first value of the array in such a reverse slice.~ (correction: the way to do this is to omit the `end` value - see below.)

What should `start` and `end` default to? Perhaps `length-1` and `-1` (literally, not in the earlier sense of a shorthand for `length-1`). For example, with these defaults `[::-1]` enumerates the whole array backwards. Unfortunately, these defaults are not consistent with the defaults when `step` is positive.

### 2. Forwards B

"forwards B" corresponds to the `for` loop:
```
for (i = start - 1; i >= end; i = i + step) {
  ...
}
```

This time `start` is re-interpreted to be the _exclusive_ starting point, `end` to be the _inclusive_ end point.

So, for example, `[2:0:-1]` applied to `[0,1,2]` produces `[1,0]`.

What should `start` and `end` default to? Perhaps `length` and `0`. For example, with these defaults `[::-1]` enumerates the whole array backwards. Again, there is a problem with these defaults in that they are not consistent with the defaults when `step` is positive.

### 3. Backwards

"backwards" corresponds to the `for` loop:
```
for (i = end - 1; i >= start; i = i + step) {
  ...
}
```

So, for example, `[0:2:-1]` applied to `[0,1,2]` produces `[1,0]`.

The same defaults of `start` and `end` can be used as when `step` was positive. So, for example, `[::-1]` enumerates the whole array backwards.

## Choosing an interpretation
What should guide the choice of interpretation? We have Göessner's original definition of JSONPath and the behaviour of the various implementations.

[Göessner](https://goessner.net/articles/JsonPath/) states:
> [JSONPath] borrows [...] the array slice syntax proposal `[start:end:step]` from ECMASCRIPT 4.

but unfortunately the corresponding links point at long since abandoned ES4 documents.

The internet archive turned up Brendan Eich’s [ES4 slice proposal](https://web.archive.org/web/20070125020659/developer.mozilla.org/es4/proposals/slice_syntax.html), which seems to favour the backwards interpretation (emphasis added):
> As in Python, a slice operator has the form `seq[start:end:step]`, where `start` is the starting index, `end` is the fencepost – one greater than the last index to slice, and `step` is the optional increment from `start` if positive **or decrement from `end` if negative**. If `start` is not given, `0` is used. If `end` is not given, `seq.length` is used. If `start` or `end` is negative, `seq.length` is added to it. After this step, any value not in `[0, seq.length]` is clamped to the nearest bound in that interval. If `step` is undefined, `1` is used; else `ToInteger(step)` must be non-zero. Any of `start`, `end`, and `step` may be omitted, and trailing colons may be omitted, but at least one colon is required to denote a “full” or “copying” slice: `seq[:]`.

What about the implementations? One comparison tests sheds some light on the matter.

[Array slice with negative step](https://cburgmer.github.io/json-path-comparison/results/array_slice_with_negative_step.html) applies the selector `$[3:0:-2]` to the array:
```
["first", "second", "third", "forth", "fifth"]
```

There is no consensus, but several implementations, including Proposal A, produce:
```
[
  "forth",
  "second"
]
```
which agrees with the "forwards A" interpretation while several others produce an empty array which agrees with the "backwards" interpretation.

**Comment by cburgmer** [comment]
Thanks for the thorough analysis.

I added another comparison [Array slice with negative step and start greater than end](https://cburgmer.github.io/json-path-comparison/results/array_slice_with_negative_step_and_start_greater_than_end.html).

I believe at the time of creating the query no implementation was returning anything meaningful for that, so I did not include it.

One more datapoint (and something users would compare to?):
```
$ python3
>>> ["first", "second", "third", "forth", "fifth"][0:3:-2]
[]
>>> ["first", "second", "third", "forth", "fifth"][3:0:-2]
['forth', 'second']
```

**Comment by remorhaz** [comment]
As for me, I've just used python (which seems to be used as a basis for ES4 slice proposal) spec/CLI to verify if my implementation works the same.

**Comment by remorhaz** [comment]
Old [2.0 docs](https://docs.python.org/2.0/ref/slicings.html) seem to contain a bit more info.

**Comment by glyn** [comment]
Unfortunately, those old [2.0 docs](https://docs.python.org/2.0/ref/slicings.html) are silent about what happens when `stride < 0`. Experimentally, Python 3 seems to adopt the "forwards A" interpretation, which makes it impossible to include the first element when the step is negative:
```
$ python3
>>> ["first", "second", "third", "forth", "fifth"][3:0:-1]
['forth', 'third', 'second']
>>> ["first", "second", "third", "forth", "fifth"][3:-1:-1]
[]
```

**Comment by cburgmer** [comment]
There is no consensus for `["first", "second", "third", "fourth", "fifth"][3::-1]` so far, but certainly a "productive" majority (as in non-empty responses) for the Python way: https://cburgmer.github.io/json-path-comparison/results/array_slice_with_open_end_and_negative_step.html

**Comment by cburgmer** [comment]
I think at this stage I would try to follow the Python implementation, minus throwing an error if nothing was found, because that's up to the underlying implementation to decide.

If we agree, are there any open questions, or do we just need to make the change in the implementation?

**Comment by glyn** [comment]
I'm not aware of other open questions, so I think it's ok to change the implementation. As a cross-check, if you bump yaml-jsonpath, its behaviour should agree with what's needed here.

**Comment by Cleidiano** [comment]
Sorry for the late interaction, but **Backwards**  seems to have advantages:
- All rules that it's applied when step is positive and already have a consensus could be applied.
- The only thing the user need to know is the direction that the operation would occur.

**Comment by glyn** [comment]
@Cleidiano I initially adopted the **Backwards** approach in my implementation because of the advantages you describe. But I changed my mind becauset the **Backwards** behaviour is probably unintuitive to programmers familiar with `for` loops. I switched to **Forwards A**.

**Comment by cburgmer** [comment]
For me the best argument so far was "follow what Python is doing". For many developers that would probably be the least surprise. If we have another widely adopted implementation out there then let's put it on the table.

**Comment by cburgmer** [comment]
Closing this, at it seems we are happy with the way Proposal A is implementing this.
