### ISSUE TITLE
Elixir_ExJsonPath and Elixir_warpath behave differently across Linux and OSX

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/json-path-comparison#58]
Running  Elixir_ExJsonPath and Elixir_warpath against the Docker image yields different output than on OSX.

Commit 03b9fe98dd6c899b6b6fcf5174d99b6c2edf768c shows the diff from a build against the Docker image.

**Comment by Cleidiano** [comment]
I don't know how to help here since I don't have a OS X to investigate what is going on, but feel free to notify me I will be happy to help here on.

**Comment by cburgmer** [comment]
Something around Elixir 1.10.3 seems to have changed. The difference stemmed from running indeed two different versions across OSX + Ubuntu.
