### ISSUE TITLE
Add other implementations

### ISSUE THREAD

**Issue by remorhaz** [cburgmer/json-path-comparison#7]
There is quite popular C++ library https://github.com/danielaparker/jsoncons that includes JsonPath implementation. It would be cool to add it to your comparison.

**Comment by cburgmer** [comment]
There's also a C# implementation, but getting dotnet to work in Docker seems to be a nightmare for now.

**Comment by cburgmer** [comment]
There is another C# implementation: https://github.com/atifaziz/JSONPath
