### ISSUE TITLE
Add scenario to check for handling of duplicate values in output

### ISSUE THREAD

**Issue by gregsdennis** [cburgmer/json-path-comparison#71]
This is prompted by https://github.com/jsonpath-standard/internet-draft/issues/23.

In short, we'd like to find out what the consensus is, if any, around removing duplicates.

Given the instance:

```json
{
  "a": [
    "string",
    null,
    true
  ],
  "b": [
    false,
    "string",
    5.4
  ]
}
```

The path `$.*[0,:5]` will select the value `"string"` three times: the child of `a` twice and the child of `b` once.

Three possible outcomes exist:

1. No duplicate elimination.  This would have three `"string"` instances in the results.
2. Value-based duplicate elimination.  This would remove all but one `"string"` instance.
3. Location-based duplicate elimination.  This would have two `"string"` instances, one from `a` and one from `b` (relates to #29).

**Comment by slandelle** [comment]
Casting my vote for 3.

**Comment by gregsdennis** [comment]
@slandelle I'm honestly not interested in what people prefer at this point.  I just want to get a test in place to see what the currently implementations actually do.

**Comment by cburgmer** [comment]
Let me know if that helps you!

**Comment by gregsdennis** [comment]
@cburgmer yeah, that does help.  Thanks.

I'll wait for that to show up in the report, then link back to it in the spec repo.

For starters, it looks like the majority just don't support it.  For those that do, it seems to be an even mix of all three approaches.  No concensus implies we're free to do whichever we like in the spec.

**Comment by cburgmer** [comment]
Do close this, if this is fixed for you, please!

**Comment by gregsdennis** [comment]
Yeah, we're good here.
