### ISSUE TITLE
Document how to run comparison natively (without Docker)

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/json-path-comparison#79]

**Comment by glyn** [comment]
Are you thinking of dropping support for the Docker-based build? I  really hope not as I don't like "polluting" a machine with all manner of language environments and then having to maintain them.

**Comment by cburgmer** [comment]
No worries, I'll keep it. I already noted your feedback before :)
I just wanted to communicate that if you run Docker you are getting second class support (which was always the case).

I'm also interested in improving it, just running out of ideas!

**Comment by cburgmer** [comment]
Closing as we are supporting both: native and with docker.

Maintaining this dual setup comes at a cost, especially as many implementations behave differently across versions (which may vary more widely in a native setup) and operating systems (OS X vs. Linux). Especially error messages seem to clutter a diff when re-running the comparison on a operating system different to the prior run.

We could just drop native support in the future, as speed becomes less of a concern once even the fastest build feels too slow to just sit idly watching.
