### ISSUE TITLE
Issue with display of queries containing the * character

### ISSUE THREAD

**Issue by danielaparker** [cburgmer/json-path-comparison#90]
The selector for the query [Dot notation with wildcard after dot notation with wildcard on nested arrays](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_wildcard_after_dot_notation_with_wildcard_on_nested_arrays.html) is
```
$.*.*
```
But on the [main comparison page](https://cburgmer.github.io/json-path-comparison/), it appears in the selector column as
```
$..
```
and the HTML for the cell is
```
<code>$.<em>.</em></code>
```
(no stars).

This appears to be an issue for all queries with the `*` character _except_ for the last query on the page
```
$[*,1]
```
which displays as expected.

**Comment by cburgmer** [comment]
This actually affects quite a few entries. Note the input and output from the markdown process:

Input
```
<tr id="dot_notation_with_wildcard_on_array" class="consensus">
[...]
<td><code>$.*</code></td>
[...]
<tr id="dot_notation_with_wildcard_on_empty_array" class="consensus">
[...]
<td><code>$.*</code></td>
```

Output
```
<tr id="dot_notation_with_wildcard_on_array" class="consensus">
[...]
<td><code>$.<em></code></td>
[...]
</tr>
<tr id="dot_notation_with_wildcard_on_empty_array" class="consensus">
[...]
<td><code>$.</em></code></td>
```

Note how `$.*` is replaced by the markdown translation with `<em>` or `</em>` depending on the (accidental) placement of the entries.
