### ISSUE TITLE
provide key for table contents

### ISSUE THREAD

**Issue by rogpeppe** [cburgmer/json-path-comparison#99]
There appears to be no information on what the entries in the table mean. Check marks and crosses are clear, and I guess "e" means "error" but what's an up arrow or a down arrow?

Example screenshot:

![image](https://user-images.githubusercontent.com/66491/135213085-48944ddf-3843-4c80-ae40-c2c85de80c9d.png)

**Comment by cburgmer** [comment]
Hey Roger, could you provide a bit more detail, I don't understand the context :)

**Comment by rogpeppe** [comment]
Oops, pressed Entry accidentally originally, and forgot to publish my edit. Fixed now.

**Comment by cburgmer** [comment]
There is an explanation at the very bottom of the page. 

Now, I assume from your feedback that it's hard to find!
Happy to change, but not sure to what :)

**Comment by rogpeppe** [comment]
I'd put the explanation at the top. I confess that I didn't think to scroll all the way to the bottom to find it (given how big the table is)

**Comment by rogpeppe** [comment]
Alternatively, a link to the raw data would work well too (e.g. in JSON or CSV format).

**Comment by cburgmer** [comment]
> As an aside, it might be nice to include some kind of summary of each column too (e.g. how many of each kind of cell), so that it's not too hard to get an idea of the quality of each implementation.

I understand, but I am afraid of giving a wrong picture here. After all this page is a lot about capturing edge cases which might not affect users equally.

**Comment by cburgmer** [comment]
I'll close this for now, with a small change made. Please do re-open if there's more we can do!
